dependencies:
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.32
- alias: prow
  name: prow
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.465
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.3793
